// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission07.Models;

namespace Mission07.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission07.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryType")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryType = "Comedy"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryType = "Drama"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryType = "Family"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryType = "Horror / Suspense"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryType = "Miscellaneous"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryType = "Television"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryType = "VHS"
                        });
                });

            modelBuilder.Entity("Mission07.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CategoryId = 2,
                            director = "Ridley Scott",
                            edited = false,
                            rating = "R",
                            title = "Gladiator",
                            year = 2000
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 2,
                            director = "Clint Eastwood",
                            edited = false,
                            rating = "R",
                            title = "American Sniper",
                            year = 2014
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryId = 3,
                            director = "Matt Reeves",
                            edited = false,
                            rating = "PG-13",
                            title = "The Batman",
                            year = 2022
                        });
                });

            modelBuilder.Entity("Mission07.Models.Movie", b =>
                {
                    b.HasOne("Mission07.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
