// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission07.Models;

namespace Mission07.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission07.Models.HomeControllerModel", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            category = "Action",
                            director = "Ridley Scott",
                            edited = false,
                            rating = "R",
                            title = "Gladiator",
                            year = 2000
                        },
                        new
                        {
                            MovieId = 2,
                            category = "Action",
                            director = "Clint Eastwood",
                            edited = false,
                            rating = "R",
                            title = "American Sniper",
                            year = 2014
                        },
                        new
                        {
                            MovieId = 3,
                            category = "Action",
                            director = "Matt Reeves",
                            edited = false,
                            rating = "PG-13",
                            title = "The Batman",
                            year = 2022
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
